# Path to fetch the metadata document
MetadataFilePath: clean_v10_metadata/cleanMetadataWithDescriptionsAndAnnotationsv1.0.xml

# List of entity types to generate swagger from.
# - Name: Name of the entity type
#   RootUri: Path to the entity in swagger document. If missing, the entity will not be exposed
#   AvailableProperty: List of properties that will be generated in the swagger document. If missing, all properties will be generated
#   NavigationPropertyMode: Mode to generate navigation properties. Possible values are:
#     - Allow: All properties from the list will be generated, properties not in the list will be ignored
#     - Ignore: All properties from the list will be ignored, properties not in the list will be generated
#     If missing, the default value is Allow
#   NavigationProperty: List of navigation properties used in the option before
#   RequiredOnWrite: List of properties that are required on write
#   ReadOnly: List of properties that are read only
EntityTypes:
  - Name: microsoft.graph.group
    RootUri: /groups
    Upsertable: true
    AvailableProperty:
      - classification
      - createdDateTime
      - description
      - displayName
      - expirationDateTime
      - groupTypes
      - isAssignableToRole
      - mail
      - mailEnabled
      - mailNickname
      - membershipRule
      - membershipRuleProcessingState
      - onPremisesDomainName
      - onPremisesLastSyncDateTime
      - onPremisesNetBiosName
      - onPremisesProvisioningErrors
      - onPremisesSamAccountName
      - onPremisesSecurityIdentifier
      - onPremisesSyncEnabled
      - preferredDataLocation
      - preferredLanguage
      - proxyAddresses
      - renewedDateTime
      - securityEnabled
      - securityIdentifier
      - serviceProvisioningErrors
      - theme
      - uniqueName
      - visibility
    NavigationProperty:
      - members
      - owners
    RequiredOnWrite:
      - displayName
      - mailEnabled
      - mailNickname
      - securityEnabled
      - uniqueName
    ReadOnly:
      - createdDateTime
      - expirationDateTime
      - mail
      - onPremisesDomainName
      - onPremisesLastSyncDateTime
      - onPremisesNetBiosName
      - onPremisesSamAccountName
      - onPremisesSecurityIdentifier
      - onPremisesSyncEnabled
      - proxyAddresses
      - renewedDateTime
  - Name: microsoft.graph.application
    RootUri: /applications
    Upsertable: true
    AvailableProperty:
      - addIns
      - api
      - appId
      - applicationTemplateId
      - appRoles
      - certification
      - createdDateTime
      - defaultRedirectUri
      - description
      - disabledByMicrosoftStatus
      - displayName
      - groupMembershipClaims
      - identifierUris
      - info
      - isDeviceOnlyAuthSupported
      - isFallbackPublicClient
      - keyCredentials
      - logo
      - notes
      - oauth2RequirePostResponse
      - optionalClaims
      - parentalControlSettings
      - passwordCredentials
      - publicClient
      - publisherDomain
      - requestSignatureVerification
      - requiredResourceAccess
      - samlMetadataUrl
      - serviceManagementReference
      - servicePrincipalLockConfiguration
      - signInAudience
      - spa
      - tags
      - tokenEncryptionKeyId
      - uniqueName
      - verifiedPublisher
      - web
    RequiredOnWrite:
      - displayName
      - uniqueName
    ReadOnly:
      - appId
      - applicationTemplateId
      - certification
      - createdDateTime
      - publisherDomain
  - Name: microsoft.graph.servicePrincipal
    RootUri: /servicePrincipals
    Upsertable: true
    AvailableProperty:
      - accountEnabled
      - addIns
      - alternativeNames
      - appDescription
      - appDisplayName
      - appId
      - appOwnerOrganizationId
      - appRoleAssignmentRequired
      - appRoles
      - applicationTemplateId
      - customSecurityAttributes
      - description
      - disabledByMicrosoftStatus
      - displayName
      - homepage
      - info
      - keyCredentials
      - loginUrl
      - logoutUrl
      - notes
      - notificationEmailAddresses
      - oauth2PermissionScopes
      - passwordCredentials
      - preferredSingleSignOnMode
      - preferredTokenSigningKeyThumbprint
      - replyUrls
      - resourceSpecificApplicationPermissions
      - samlSingleSignOnSettings
      - servicePrincipalNames
      - servicePrincipalType
      - signInAudience
      - tags
      - tokenEncryptionKeyId
      - verifiedPublisher
    RequiredOnWrite:
      - appId
    ReadOnly:
      - applicationTemplateId
      - resourceSpecificApplicationPermissions
      - signInAudience
  - Name: microsoft.graph.federatedIdentityCredential
    RootUri: /applications/federatedIdentityCredentials
    Upsertable: true
    ContainerEntitySet: applications
    AvailableProperty:
      - audiences
      - description
      - issuer
      - name
      - subject
    RequiredOnWrite:
      - audiences
      - issuer
      - name
      - subject
  - Name: microsoft.graph.oAuth2PermissionGrant
    RootUri: /oauth2PermissionGrants
    Upsertable: false
    Updatable: true
    AvailableProperty:
      - clientId
      - consentType
      - principalId
      - resourceId
      - scope
    RequiredOnWrite:
      - clientId
      - consentType
      - resourceId
    FilterProperty:
      - clientId
      - consentType
      - resourceId
    CompositeKey:
      - clientId
      - consentType
      - resourceId
  - Name: microsoft.graph.appRoleAssignment
    RootUri: /appRoleAssignedTo
    Upsertable: false
    Updatable: false
    ContainerEntitySet: servicePrincipals
    ContainerKeyProperty: resourceId
    AvailableProperty:
      - appRoleId
      - createdDateTime
      - principalDisplayName
      - principalId
      - principalType
      - resourceDisplayName
      - resourceId
    RequiredOnWrite:
      - appRoleId
      - principalId
      - resourceId
    ReadOnly:
      - createdDateTime
      - principalDisplayName
      - principalType
    FilterProperty:
      - resourceId
    CompositeKey:
      - appRoleId
      - resourceId
  - Name: microsoft.graph.appRole
    ReadOnly:
      - origin
  - Name: microsoft.graph.informationalUrl
    ReadOnly:
      - logoUrl
  - Name: microsoft.graph.passwordCredential
    AvailableProperty:
      - displayName
      - endDateTime
      - hint
      - keyId
      - secretText
      - startDateTime
    ReadOnly:
      - hint
      - secretText
  - Name: microsoft.graph.directoryObject
    ReadOnly:
      - deletedDateTime
  - Name: microsoft.graph.entity
    ReadOnly:
      - id
  - Name: microsoft.graph.subscription
    RootUri: /subscriptions
    AvailableProperty:
      - applicationId
      - changeType
      - clientState
      - creatorId
      - encryptionCertificate
      - encryptionCertificateId
      - expirationDateTime
      - includeResourceData
      - latestSupportedTlsVersion
      - lifecycleNotificationUrl
      - notificationQueryOptions
      - notificationUrl
      - notificationUrlAppId
      - resource
    RequiredOnWrite:
      - changeType
      - expirationDateTime
      - notificationUrl
      - resource
    ReadOnly:
      - applicationId
      - creatorId
